version: '2.1'

networks:
  nod-newscrawler:

services:
  crawler:
    image: uhhlt/newscrawler
    restart: on-failure
    networks:
      nod-newscrawler:
    volumes:
      - ${PWD}/out:/app/out
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=changeme
      - CRAWLER_FEEDS_FILE=/app/data/feeds_de.txt
      - CRAWLER_LANGUAGE=german
      - CRAWLER_TIMEZONE=Europe/Berlin

  elasticsearch:
    image: elasticsearch:5.5.2-alpine
    networks:
      nod-newscrawler:
    volumes:
      - ${PWD}/elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:5.5.2
    networks:
      nod-newscrawler:
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  nodcore:
    image: uhhlt/nodcore
    volumes:
      - ${PWD}/out/nod/german:/app/content
    depends_on:
          db:
            condition: service_healthy
    networks:
      nod-newscrawler:

  nodweb:
    image: uhhlt/nodweb
    restart: always
    ports:
      - 10008:9000
    depends_on:
          db:
            condition: service_healthy
    networks:
      nod-newscrawler:

  db:
      image: mariadb
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=nodcore
        - MYSQL_USER=nod
        - MYSQL_PORT=3306
        - MYSQL_PASSWORD=nod
      volumes:
        - ${PWD}/nod-data/:/var/lib/mysql
        - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pnod", "-unod"]
        interval: 20s
        timeout: 10s
        retries: 10
      networks:
        nod-newscrawler:

